hacknews/core/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from . import views

app_name = "core"


urlpatterns = [
    path("", views.index, name="index"),
    path("new/", views.new, name="new"),
    path("signup/", views.signup, name="signup"),
    path("login/", LoginView.as_view(template_name="core/login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
]

hacknews/hacknews/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    path("", include("story.urls")),
]

hacknews/story/urls.py
from django.urls import path

from . import views

app_name = "story"


urlpatterns = [
    path("create/", views.create, name="create"),
    path("<int:pk>/", views.detail, name="detail"),
    path("<int:pk>/vote/", views.vote, name="vote"),
    path("<int:pk>/unvote/", views.unvote, name="unvote"),
]

hacknews/core/models.py
from django.db import models

# Create your models here.

hacknews/story/models.py
from django.contrib.auth.models import User
from django.db import models


class Story(models.Model):
    title = models.CharField(max_length=255)
    url = models.URLField(blank=True, null=True)
    text = models.TextField(blank=True, null=True)
    number_of_votes = models.IntegerField(default=0)

    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(
        User, related_name="stories", on_delete=models.CASCADE
    )


class Comment(models.Model):
    story = models.ForeignKey(Story, related_name="comments", on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(
        User, related_name="comments", on_delete=models.CASCADE
    )


class Vote(models.Model):
    story = models.ForeignKey(Story, related_name="votes", on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(
        User, related_name="story_votes", on_delete=models.CASCADE
    )

hacknews/story/forms.py
from django.forms import ModelForm

from .models import Comment, Story


class StoryForm(ModelForm):
    class Meta:
        model = Story
        fields = (
            "title",
            "url",
            "text",
        )


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ("text",)

hacknews/core/views.py
import datetime

from django.contrib.auth.forms import UserCreationForm
from django.db.models import Count
from django.shortcuts import redirect, render
from story.models import Story


def index(request):
    today = datetime.date.today()
    stories = Story.objects.filter(created_at__gte=today).order_by("-number_of_votes")[
        0:30
    ]

    if request.user.is_authenticated:
        for story in stories:
            story.has_voted = False

            if story.votes.filter(created_by=request.user):
                story.has_voted = True

    return render(request, "core/index.html", {"stories": stories})


def new(request):
    today = datetime.date.today()
    stories = Story.objects.filter(created_at__gte=today).order_by("-created_at")

    if request.user.is_authenticated:
        for story in stories:
            story.has_voted = False

            if story.votes.filter(created_by=request.user):
                story.has_voted = True

    return render(request, "core/new.html", {"stories": stories})


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/login/")
    else:
        form = UserCreationForm()
    return render(request, "core/signup.html", {"form": form})

hacknews/story/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render

from .forms import CommentForm, StoryForm
from .models import Comment, Story, Vote


def detail(request, pk):
    story = Story.objects.get(pk=pk)

    story.has_voted = False

    if story.votes.filter(created_by=request.user):
        story.has_voted = True

    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid:
            comment = form.save(commit=False)
            comment.story = story
            comment.created_by = request.user
            comment.save()
            return redirect("story:detail", pk=pk)
    else:
        form = CommentForm()

    return render(request, "story/detail.html", {"story": story, "form": form})


@login_required
def vote(request, pk):
    story = Story.objects.get(pk=pk)

    already_voted = story.votes.filter(created_by=request.user)

    if not already_voted:
        Vote.objects.create(story=story, created_by=request.user)

        story.number_of_votes = story.number_of_votes + 1
        story.save()

    redirect_page = request.GET.get("redirect_page", "/")

    if redirect_page == "detail":
        return redirect("story:detail", pk=pk)

    else:
        return redirect(redirect_page)


@login_required
def unvote(request, pk):
    story = Story.objects.get(pk=pk)

    vote = Vote.objects.get(story_id=pk, created_by=request.user)
    vote.delete()

    story.number_of_votes = story.number_of_votes - 1
    story.save()

    redirect_page = request.GET.get("redirect_page", "/")

    if redirect_page == "detail":
        return redirect("story:detail", pk=pk)

    else:
        return redirect(redirect_page)


@login_required
def create(request):
    if request.method == "POST":
        form = StoryForm(request.POST)
        if form.is_valid:
            story = form.save(commit=False)
            story.created_by = request.user
            story.save()
            return redirect("/")
    else:
        form = StoryForm()

    return render(request, "story/create.html", {"form": form})

hacknews/core/templates/core/base.html
<!doctype html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>{% block title %}{% endblock %} | Hack News </title>
</head>

<body>
    <div class="max-w-4xl mx-auto p-1">
        <nav class="p-1 flex items-center justify-between bg-orange-400">
            <div>
                <a href="{% url 'core:index' %}" class="mr-2 font-bold">Hacker News</a>
                <a href="{% url 'core:new' %}">new</a> |
                <a href="{% url 'story:create' %}">submit</a> |

            </div>
            <div>
                {% if request.user.is_authenticated %}
                <a href="#">{{ request.user.username }}</a> |
                <a href="{% url 'core:logout' %}">logout</a>

                {% else %}
                <a href="{% url 'core:login' %}">login</a> |
                <a href="{% url 'core:signup' %}">signup</a>
                {% endif %}
            </div>
        </nav>

        <main class="bg-orange-100">
            {% block content %}

            {% endblock %}
        </main>

        <footer>

        </footer>
    </div>
</body>

</html>

hacknews/core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}
Welcome
{% endblock %}

{% block content %}

{% for story in stories %}
<div class="p-2 flex">
    <div class="flex">
        <p class="text-gray-500">{{forloop.counter}}.</p>
        {% if not story.has_voted %}
        <a href="{% url 'story:vote' story.id %}?redirect_page=core:index" class="text-gray-500">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                stroke="currentColor" class="w-6 h-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M4.5 15.75l7.5-7.5 7.5 7.5" />
            </svg>
        </a>
        {% endif %}
    </div>

    <div>
        <a href="{% url 'story:detail' story.id %}">
            <p>{{ story.title }}
        </a>
        {% if story.url %}
        <a href="{{ story.url }}" class="text-gray-500">({{ story.url }})</a>
        {% endif %}
        </p>
        <div class="flex text-gray-500">
            <p>
                {{ story.number_of_votes }} points by {{ story.created_by.username }} {{story.created_at|timesince}}
            </p>
            <p class="px-3">|</p>
            <p>
                {{ story.comments.count }} comments
            </p>

            {% if story.has_voted %}
            <p class="px-3">|</p>
            <a href="{% url 'story:unvote' story.id %}?redirect_page=core:index" class="text-gray-500">
                Unvote
            </a>
            {% endif %}
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

hacknews/core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}
Log in
{% endblock %}

{% block content %}
<div class="p-2">
    <h1 class="mb-4 font-bold">Log in</h1>

    <form method="post" action=".">
        {% csrf_token %}

        {{ form.as_p }}
        <button class="mt-5 p-1 rounded-sm border border-color-gray-500 bg-gray-100">Submit</button>
    </form>
</div>
{% endblock %}

hacknews/core/templates/core/new.html
{% extends 'core/base.html' %}

{% block title %}
New
{% endblock %}

{% block content %}

{% for story in stories %}
<div class="p-2 flex">
    <div class="flex">
        <p class="text-gray-500">{{forloop.counter}}.</p>

        {% if not story.has_voted %}
        <a href="{% url 'story:vote' story.id %}?redirect_page=core:new" class="text-gray-500">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                stroke="currentColor" class="w-6 h-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M4.5 15.75l7.5-7.5 7.5 7.5" />
            </svg>
        </a>
        {% endif %}
    </div>

    <div>
        <a href="{% url 'story:detail' story.id %}">
            <p>{{ story.title }}
        </a>
        {% if story.url %}
        <a href="{{ story.url }}" class="text-gray-500">({{ story.url }})</a>
        {% endif %}
        </p>
        <div class="flex text-gray-500">
            <p>
                {{ story.number_of_votes }} points by {{ story.created_by.username }} {{story.created_at|timesince}}
            </p>
            <p class="px-3">|</p>
            <p>
                {{ story.comments.count }} comments
            </p>
            {% if story.has_voted %}
            <p class="px-3">|</p>
            <a href="{% url 'story:unvote' story.id %}?redirect_page=core:new" class="text-gray-500">
                Unvote
            </a>
            {% endif %}
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

hacknews/core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}
Sign up
{% endblock %}

{% block content %}
<div class="p-2">
    <h1 class="mb-4 font-bold">Sign up</h1>

    <form method="post" action=".">
        {% csrf_token %}

        {{ form.as_p }}
        <button class="mt-5 p-1 rounded-sm border border-color-gray-500 bg-gray-100">Submit</button>
    </form>
</div>
{% endblock %}

hacknews/story/templates/story/create.html
{% extends 'core/base.html' %}

{% block title %}
Create story
{% endblock %}

{% block content %}
<div class="p-2">
    <h1 class="mb-4 font-bold">Create story</h1>

    <form method="post" action=".">
        {% csrf_token %}

        {{ form.as_p }}
        <button class="mt-5 p-1 rounded-sm border border-color-gray-500 bg-gray-100">Submit</button>
    </form>
</div>
{% endblock %}

hacknews/story/templates/story/detail.html
{% extends 'core/base.html' %}

{% block title %}
{{ story.title }}
{% endblock %}

{% block content %}
<div class="p-2 flex">
    {% if not story.has_voted %}
    <a href="{% url 'story:vote' story.id %}?redirect_page=detail" class="text-gray-500">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor"
            class="w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M4.5 15.75l7.5-7.5 7.5 7.5" />
        </svg>
    </a>
    {% endif %}

    <div>
        <a href="{% url 'story:detail' story.id %}">
            <p>{{ story.title }}
        </a>
        {% if story.url %}
        <a href="{{ story.url }}" class="text-gray-500">({{ story.url }})</a>
        {% elif story.text %}
        <p>{{ story.text }}</p>
        {% endif %}
        </p>
        <div class="flex text-gray-500">
            <p>
                {{ story.number_of_votes }} points by {{ story.created_by.username }} {{story.created_at|timesince}}
            </p>
            <p class="px-3">|</p>
            <p>
                {{ story.comments.count }} comments
            </p>
            {% if story.has_voted %}
            <p class="px-3">|</p>
            <a href="{% url 'story:unvote' story.id %}?redirect_page=detail" class="text-gray-500">
                Unvote
            </a>
            {% endif %}
        </div>
    </div>
</div>

<div class="p-2">
    {% if request.user.is_authenticated %}
    <form method="post" action=".">
        {% csrf_token %}

        {{ form.as_p }}

        <button class="mt-5 p-1 rounded-sm border border-color-gray-500 bg-gray-100">Submit</button>

    </form>
    {% else %}
    <p>You need to log in to submit a comment!</p>

    {% endif %}
</div>
<div class="p-2">
    {% for comment in story.comments.all %}
    <div class="p-2">
        <p class="text-gray-500">
            {{ comment.created_by.username }}
            |
            {{ comment.created_at|timesince }} ago
        </p>

        <p class="mt-2">
            {{ comment.text }}
        </p>
    </div>
    {% endfor %}
</div>
{% endblock %}